---
- name: Create google cloud instance
  hosts: localhost
  become: true
  vars_files:
    - ../vars/vault-data--credentail.yaml
  vars:
    machine_name: master1
    service_account_path: ../google-service-account.json
    ssh_public_key_path: /home/bunpanin/.ssh/id_rsa.pub
  tasks:
    - name: create first gcp instance
      import_tasks: tasks/create-gcp-task.yaml


# ansible-playbook playbooks/crWriteeate-gcp-instance.yaml