# Combining all playbooks into one playbooks
---
- name: Setup NFS server
  import_playbook: nfs_server.yaml
- name: Setup NFS client
  import_playbook: nfs_client.yaml
- name: Run spring boot media service
  import_playbook: spring_compose

# ansible-playbook -i inventory.ini playbooks/nsf_main.yamlcom