# Combining all playbooks into one playbooks
---
- name: Setup NFS server
  import_playbook: nfs_server.yaml
- name: Setup NFS client
  import_playbook: nfs_client.yaml

# ansible-playbook -i inventory.ini playbooks/nsf_main.yamlcom