# service_account_path: "/home/bunpanin/credentials/service-account.json"
service_account_path: "/home/bunpanin/she-gone/ansible/iaC/credentails/google-service-account.json"
google_project_id: "digital-elysium-484213-d4"
ssh_pubkey_path: "/home/bunpanin/.ssh/id_rsa.pub"

# Define machine spec
machine_specs:
  large:
    machine_type: "e2-standard-2"
    # machine_type: "e2-medium"
    # zone: "asia-southeast1-a"
    zone: "asia-southeast1-b"
    disk_size: 20
    disk_type: "pd-standard" # we have hdd(pd-standard) , ssd( pd-ssd)
  medium:
    machine_type: "e2-medium"
    zone: "asia-southeast1-b"
    disk_size: 20
    disk_type: "pd-standard"

ubuntu_specs:
  v22:
    image: "projects/ubuntu-os-cloud/global/images/family/ubuntu-2204-lts"
  v24:
    image: "projects/ubuntu-os-cloud/global/images/family/ubuntu-2404-lts"
# Define machines that we will create
machines_info:
  # master requirement : RAM 8G, ....
  - name: "master01"
    machine_type: "{{ machine_specs.large.machine_type }}"
    image: "{{ ubuntu_specs.v22.image }}"
    zone: "{{ machine_specs.large.zone }}"
    disk_size: "{{ machine_specs.large.disk_size }}"
    disk_type: "{{ machine_specs.large.disk_type }}"
  - name: "worker01"
    machine_type: "{{ machine_specs.medium.machine_type }}"
    image: "{{ ubuntu_specs.v22.image }}"
    zone: "{{ machine_specs.medium.zone }}"
    disk_size: "{{ machine_specs.medium.disk_size }}"
    disk_type: "{{ machine_specs.medium.disk_type }}"
  - name: "worker02"
    image: "{{ ubuntu_specs.v22.image }}"
    machine_type: "{{ machine_specs.medium.machine_type }}"
    zone: "{{ machine_specs.medium.zone }}"
    disk_size: "{{ machine_specs.medium.disk_size }}"
    disk_type: "{{ machine_specs.medium.disk_type }}"